import calculator
print(calculator.add2())
# print(calculator.add3())
# print(calculator.add4())
# print(calculator.add5())
# print(calculator.sub2())
# print(calculator.sub3())
# print(calculator.sub4())
# print(calculator.sub5())
# print(calculator.mul2())
# print(calculator.mul3())
# print(calculator.mul4())
# print(calculator.mul5())
# print(calculator.div2())
# print(calculator.div3())
# print(calculator.div4())
# print(calculator.div5())
